# Generated by Django 5.2.8 on 2025-11-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('manager_1', 'manager_1'), ('manager_2', 'manager_2'), ('finance', 'finance')], default='staff', max_length=30),
        ),
    ]
