# Generated by Django 5.2.8 on 2025-11-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'finance')]),
        ),
    ]
